### ISSUE TITLE
Wrong LOC

### ISSUE THREAD

**Issue by mjureczko** [mjureczko/CKJM-extended#1]
I am extracting metrics from 13 differ4ence projects, all on SVN. Once I create JAR files for each project, I used the tool as stated in the documentation, but it kept giving me the wrong LOC ! Any ideas of what may be the reason ?

I am using it with http://projects.apache.org/projects/axis2.html
The investigated jar file: http://fileshark.pl/pobierz/5178113/3e2a6/axis2-transport-testkit-1-7-0-snapshot-jar

**Comment by mjahmad** [comment]
I think the issue has been resolved as CKJM looks at the binary giles rather than the code.
