### ISSUE TITLE
Getting ClassNotFoundException !!!!!

### ISSUE THREAD

**Issue by mjahmad** [mjureczko/CKJM-extended#2]
I am using ckjm to extract metrics from huge projects, so i use the command below to include all the classes in the my project. Ive been getting results, but also been getting ClassNotFoundException : Error while looking for class. I am not an expert, but when i checked the location of the "missing" class, i find the class there. I know this has to do with classpath, but i am still confused. Any guidance would be appreciated.

find c:\myproject -name '*.class' | java -jar c:\ckjm_ext.jar

**Comment by mjureczko** [comment]
The ClassNotFoundException is usually thrown when the investigated classes depends on libraries that are not available in the classpath. Please, try to calculate the metrics once more, this time with the classpath configured and let me know if it is that case. If you are investigating a maven project you can generate the classpath automatically: https://maven.apache.org/plugins/maven-dependency-plugin/build-classpath-mojo.html.
