### ISSUE TITLE
Value mismatch of CC in the generated XML file

### ISSUE THREAD

**Issue by mjahmad** [mjureczko/CKJM-extended#3]
I am generating a XML file -using the code below- with all the metrics. When i compare the values of the CC metrics from the command line with the same value in the XML, i realized they are not the same. 
When running the tool in the command line, i ge the following:
testtoy 2 1 0 1 11 1 0 1 2 2.0000 36 0.0000 0 0.0000 0.5000 0 0 17.0000
 ~ public static void main(String[] arg0): 2
 ~ public void <init>(): 1  (when exported to xml, this value is 0, not 1 ) !!!!

![ckjm](https://cloud.githubusercontent.com/assets/12873559/8358301/7bf5ac9e-1b2d-11e5-8fec-1255037ed6d7.jpg)

**Comment by mjureczko** [comment]
Could you attach the testtoy.class or paste its source code?

**Comment by mjahmad** [comment]
This requires the jar file "commons-math3-3.3.jar" to run, download it http://commons.apache.org/proper/commons-math/download_math.cgi

 Here is the code : 

/*  Computes the slope of a simple linear regression line for an array of 2D
	data points.
*/

import org.apache.commons.math3.stat.regression.SimpleRegression;

//###############################################################################
public class testtoy
{
    public static void main (String args[])
    {
		SimpleRegression sReg = new SimpleRegression();
		for (int i = 0; i < 50; i++)
			sReg.addData(i, i);
		double m = sReg.getSlope();
		System.out.println("slope = " + m);
    }// end method main
}// end class test-toy
